### ISSUE TITLE
Smart Button onError callback not firing

### ISSUE THREAD

**Issue by JasonTheAdams** [paypal/paypal-sdk-client#45]
Greetings!

We're tightening up our integration by making sure we've got error handling locked down. I'm having trouble getting the `onError` callback on the `paypal.Buttons(config)` to work properly. Here's the thing, though, it's working just fine in this codepen I threw together: https://codepen.io/JasonTheAdams/pen/gOrKyoG

Clearly we're doing something different. Here's what we've got in the application:
```js
		paypal.Buttons( {
			onInit: onInitHandler,
			onClick: onClickHandler,
			createOrder: createOrderHandler,
			onApprove: onApproveHandler,
			onError: function( error ) {
				console.log( 'In this function' );
				console.log( error );
			},
			style: {
				layout: 'vertical',
				size: 'responsive',
				shape: 'rect',
				label: 'paypal',
				color: 'gold',
				tagline: false,
			},
		} ).render( this.smartButtonContainer );
```

As you can see, I've just got a closure for `onError`, however "In this function" never shows up in the console. Here's our `createOrderHandler` method which throws the error:
```js
	async createOrderHandler( data, actions ) {
		Give.form.fn.removeErrors( this.jQueryForm );

		const response = await fetch( `${ Give.fn.getGlobalVar( 'ajaxurl' ) }?action=give_paypal_commerce_create_order`, {
			method: 'POST',
			body: DonationForm.getFormDataWithoutGiveActionField( this.form ),
		} );

		const responseJson = await response.json();

		if ( ! responseJson.success ) {
			if ( null === responseJson.data.error ) {
				throw {};
			}

			throw responseJson.data.error;
		}

		return responseJson.data.id;
	}
```

It is throwing the error, and I see the following show up in the console:
![image](https://user-images.githubusercontent.com/2024145/93155831-cd2fca80-f6bb-11ea-953a-0037c18f7f01.png)

Any ideas as to why the `onError` callback may not be getting fired?

**Comment by mnicpt** [comment]
@JasonTheAdams I will take a look at it and get back to you.  Thank you for sharing.

**Comment by mnicpt** [comment]
@JasonTheAdams I'm seeing this message in the logs: `Partner Policy config not found for request`.   Also, try to throw an error at the first line of the createOrderHandler and see if it catches it.

**Comment by JasonTheAdams** [comment]
@mnicpt We figured out the issue. It turns out that if the `onClick` option is used, then `onError` no longer works. You can see this in my codepen: https://codepen.io/JasonTheAdams/pen/gOrKyoG — if you comment out the `onClick` option then `onError` starts working.

**Comment by JasonTheAdams** [comment]
To be clear, in our case we need to use both `onClick` and `onError`, so this is a blocker for us.

**Comment by JasonTheAdams** [comment]
@mnicpt As an update, we are coordinating with our PayPal Sr. Integration Engineer to aim to launch in a couple of weeks. We have another bug on PayPal's side going live on the 30th. If it's at all possible to have a fix in place before then, that would be incredibly helpful. Having the ability to catch and present errors meaningfully to our users is important.

Thanks!

**Comment by mnicpt** [comment]
@JasonTheAdams Can you send me the code that is being executed in the onClickHandler?

**Comment by mnicpt** [comment]
@JasonTheAdams Also want to mention that the `onError` function will only be called for errors occurring inside our libraries and not from custom code.  I ran the pen above and I don't see the `onError` function being called.  An example of this error may come from the `orderId` not being passed to the `onApprove` call or the `token` is not being passed to `createOrder`.  If you are expecting and error to be caught from your custom code, we don't support that through the `onError` function.

**Comment by JasonTheAdams** [comment]
Hi @mnicpt! That's the point of the pen above. 😉 If you comment out the `onClick: function() { }` line then you'll see that `onError` works as expected.

It does seem to me that whatever calls `onError` is simply catching JS Errors that get thrown — which is great!

**Comment by JasonTheAdams** [comment]
Just to help make it clear:
![onClick issue](https://p179.p0.n0.cdn.getcloudapp.com/items/eDuBNEzL/Screen%20Recording%202020-09-21%20at%2003.06.18%20PM.gif?v=059c0b45ce4fc6ef9d4425c781bc2f55)

**Comment by bluepnume** [comment]
Yep there's definitely an inconsistency we need to fix here. We may need a few days to dig into this and figure out what the best fix is, and that we're consistently returning the right kind of errors (whether or not onClick is passed)

**Comment by JasonTheAdams** [comment]
Awesome, thank you! 🙌

**Comment by mnicpt** [comment]
> Hi @mnicpt! That's the point of the pen above. 😉 If you comment out the `onClick: function() { }` line then you'll see that `onError` works as expected.
> 
> It does seem to me that whatever calls `onError` is simply catching JS Errors that get thrown — which is great!
> 
> Also, to answer your question, the error is being thrown in `createOrder`, just like in that pen. The issue isn't with what's in our `onClick` callback, as even an empty callback causes the issue.

My bad.  My head was spinning yesterday looking at why this was occurring.  As Daniel mentioned above, and after much exploration yesterday, we want to make sure that we do this right and will let you know when we have this ready for you.  Thanks again, @JasonTheAdams .

**Comment by JasonTheAdams** [comment]
> My bad. My head was spinning yesterday looking at why this was occurring. As Daniel mentioned above, and after much exploration yesterday, we want to make sure that we do this right and will let you know when we have this ready for you. Thanks again, @JasonTheAdams .

Not a problem at all. Thank you for your efforts. 😄

**Comment by mnicpt** [comment]
@JasonTheAdams I know you mentioned above about launching in a couple of weeks.  The fix for this is not trivial and will most likely take longer than that alongside the other prioritized work.  Would you be able, for the short-term, try-catch any errors for now and then can have a more reliable `onError` function once we get the fix released?

**Comment by JasonTheAdams** [comment]
@mnicpt I see, that's unfortunate. We're slated to launch the second week of October. You don't think it will be done by then? If not, we'll have to see what we can do to workaround it.

**Comment by mnicpt** [comment]
@JasonTheAdams It's more that it's not clear and can't commit to a date.  We will certainly do our best.

**Comment by bluepnume** [comment]
@JasonTheAdams if it's a matter of unblocking your launch, can you just do something like:

```
const errorHandler = (err) => {
    // ...
}

paypal.Buttons({
    createOrder: () => {
        return fetch().then(() => {
            // ...
        }).catch(errorHandler);
    },
    onError: errorHandler
})
```

**Comment by JasonTheAdams** [comment]
Thanks, @bluepnume, we'll give that a shot. It does, of course, mean that we'll miss any errors that happen outside of the `createOrder` function — say if there's an issue after the order is provided to the SDK.

**Comment by mnicpt** [comment]
@JasonTheAdams A fix for this has been released.  Please check to see if that has fixed your issue.  I will close for now but feel free to reopen if you are still seeing issues.

**Comment by JasonTheAdams** [comment]
@mnicpt Awesome! I see that my codepen is working now. Thank you!
