### ISSUE TITLE
Invalid authorization code

### ISSUE THREAD

**Issue by williamyaowu** [paypal/paypal-sdk-client#51]
we just noticed that, when use paypal authentication. it will return authorization code. But to some specifc user, when we use this authorization code to exchange token, it always report 400, and the payload would like:
{"error_description":"Invalid authorization code","error":"access_denied","correlation_id":"2ac9f7fa4e099","information_link":"https://developer.paypal.com/docs/api/#errors"}

**Comment by gregjopa** [comment]
Hi @williamyaowu if you are still having an issue please open up a new github issue here: https://github.com/paypal/paypal-checkout-components/
